APP_NAME = "FastAPI-Demo"
API_HEADER_PASSWORD = ""

[POSTGRESQL_SETTINGS]
HOST = "localhost"
PORT = "5432"
USERNAME = "postgres"
PASSWORD = "fastapi"
DATABASE = "fast_api_demo"

[AUTH2_SETTINGS]
SECRET_KEY = "b6f86a1ebc8beb34f36edec1c1ef5468c56d41e781ac9242fa52796e7fa372f8"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60