APP_NAME = "$APP_NAME"
API_HEADER_PASSWORD = "$API_HEADER_PASSWORD"

[POSTGRESQL_SETTINGS]
HOST = "$POSTGRESQL_SETTINGS_HOST"
PORT = "$POSTGRESQL_SETTINGS_PORT"
USERNAME = "$POSTGRESQL_SETTINGS_USERNAME"
PASSWORD = "$POSTGRESQL_SETTINGS_PASSWORD"
DATABASE = "$POSTGRESQL_SETTINGS_DATABASE"

[AUTH2_SETTINGS]
SECRET_KEY = "$AUTH2_SETTINGS_SECRET_KEY"
ALGORITHM = "$AUTH2_SETTINGS_ALGORITHM"
ACCESS_TOKEN_EXPIRE_MINUTES = $AUTH2_SETTINGS_ACCESS_TOKEN_EXPIRE_MINUTES