version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - CURRENT_ENV=DOCKER
      - APP_NAME=FastAPI-Demo
      - API_HEADER_PASSWORD=
      - POSTGRESQL_SETTINGS_HOST=db
      - POSTGRESQL_SETTINGS_PORT=5432
      - POSTGRESQL_SETTINGS_PASSWORD=fastapi
      - POSTGRESQL_SETTINGS_DATABASE=fast_api_demo
      - POSTGRESQL_SETTINGS_USERNAME=postgres
      - AUTH2_SETTINGS_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - AUTH2_SETTINGS_ALGORITHM=HS256
      - AUTH2_SETTINGS_ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres
#    expose:
#      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fast_api_demo
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: